spring:
  datasource:
    username: root
    password: 1230123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/email

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  thymeleaf:
    cache: false
    mode: HTML5