spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/email

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  thymeleaf:
    cache: false
    mode: HTML5

  security:
    user:
      name: admin
      password: admin

  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/, classpath:/templates/pages/